## C++ Exception 

* throw 한 위치에서 즉시 함수가 종료된다. 
    * 예외를 처리하는 부분까지 jump 
    * throw 밑의 모든 코드는 실행되지 않는다. 
    * 함수에서 예외 처리하는 부분에 도달하기 까지 함수를 빠져나가면서 stack 에 생성되었던 객체들을 빠짐없이 소멸시켜줌. 
    * 소멸자만 제대로 작성했다면, 자원을 제대로 소멸시킬 수 있음. 

* `out_of_range` 예시 
    
    ```
    if(index >= size){
        throw std::out_of_range("index out of range error"); 
    }
    
    //throw 다음으로 catch 가 실행 
    
    catch(std::out_of_range& e){
        std::cout << "exception occured" << e.what() << std::endl; 
    }
    ```

* 
 

## 명품 C++ 연습문제 : 예외처리 

* page 674 ~ 678 

### 이론 문제 
1. 프로그램 실행 중 오작동이나 결과에 영향을 미치는 실행 오류 발생은 ? 
    * 예외 Exception (정답 1번)
    
2. 예외 처리 관련 키워드 아닌 것? 
    * try, throw, catch (0)
    * except 는 아님 (정답 3번)
    
3. 하나의 try{}블록에 연결되는 catch(){}블록은 ? 
    * 여러 개 만들 수 있다. (정답 3번)
    
4. catch(){} 블록에 대해 틀린 설명은? 
    * throw 문에서 던진 예외를 처리하는 블록 (0)
    * 예외 파라미터는 매개변수 선언과 동일, 매개변수는 오직 하나만 선언가능? (*)
    * catch(){}블록은 예외 처리한 다음 실행을 중단한다 (X)
    * 하나의 catch(){} 블록은 오직 하나의 예외 타입만 처리 (0) 
        
5. 다음 코드의 실행 결과는 ? 

    ```
    int m = 3; 
    try{
    throw &m; 
    } 
    catch(int * y){
    *y = 100; 
    cout << m; 
    }
    ```
    * 정답 : 100 
    
6. 다음 코드의 실행 결과는 ? 

    ```
    try{
        throw 3; 
    }catch(int x){
        try{
            cout << x; 
            throw "aa"; 
        }catch(const char * p){
            cout << p; 
        }
    }
    ```  
    
    * 정답 : 3 aa 

7. 다음 프로그램의 실행 결과는 ? 

    ```
    try{
        throw 3; 
    }
    catch(int x){
        try{
            throw x + 1; 
            cout << x; 
        }catch(int y){
            cout << y; 
        }
    }
    ```
    
    * 정답 : 4 4 
    
8. 다음 각 문항에 따라 다음 프로그램의 실행 결과는 ? 
    
    ```
    int n, m; 
    try{
        if(n == 0){
            throw "0을 다루지 않음"; 
        }
        if(m%n == 0){
            throw 0; 
        }
        cout << m % n; 
    }
    catch(int x){
        cout << x;
    }
    catch(const char * s){
        cout << s; 
    }
    ```
    > (1) n = 0; m = 5; 
    * 정답 : "0을 다루지 않음"
    > (2) n = 5; m = 10; 
    * 정답 : 0 
    > (3) n = 6; m = 10; 
    * 정답 : 4 
    
9. 다음 함수가 있다. 

    ```
    void printDouble(int m){
        try{
            if(m<0) throw m; 
            else m = m*2; 
        }catch(int y){
            cout << "음수는 다루지 않음"; 
        }
        cout << m << endl; 
    }
    ```
    > (1) printDouble(5); 
    * 결과 : 25
    > (2) printDouble(-3); 
    * 결과 : "음수는 다루지 않음"
    
10. 다음 코드를 실행하면 어떻게 되는가? 

    ```
    int n = 20; 
    throw n; 
    try{
        n = n/2; 
    }
    catch(int x){
        cout << n; 
    }
    ```
    
    * 정답 : 20 
    
11. throw() 지시어를 덧붙여 다음 함수를 선언하라. (???)

    ```
    int get() throw(char*){
        int n; 
        cout << "0에서 10까지의 수를 입력 >> "
        cin >> n;  
        if(n < 0) throw "음수 입력 불가"; 
        if(n > 10) throw "너무 큰 숫자";
        return n; 
    }
    ```
    
12. 다음 함수 선언문의 의미는 무엇인가? 
    ```
    int big(int x, int y) throw(int); 
    ```
    
    * 정답 : 매개변수로 정수 2개를 받고, 정수 하나의 값에 대해 예외 처리를 해주겠다는 뜻 
    
13. 다음과 같이 선언된 함수에 대해 잘 설명한 것은? 

    ```
    int open(string name, int mode) throw(int, char*); 
    ```
    - (1) open 함수가 실행되는 동안 반드시 예외 발생? (X)
    - (2) open 함수가 발생시키는 예외는 int타입과 char* 타입 두종류뿐 (O)
    - (3) open 함수는 예외 처리를 했기 때문에 실행 오류가 발생하지 않는다 (X)
    - (4) open 함수의 매개 변수에 값이 잘못 넘어오면 그때 예외가 발생한다. (X) 
    
14. 다음 함수는 어떤 부분이 잘못되었는가? 

    ```
    bool isEven(int x) throw(bool){
        if(x < 0) throw "음수 예외 발생"; 
        if(x % 2) return true; 
        else return false; 
    }
    ```
    * 정답 : throw(bool) 인데, 그 값을 catch 해주는 구문이 없다 ? 
    
15. 컴파일러가 소스 파일을 컴파일하여 object 코드를 만들 때, source file 내의 변수, 함수, 클래스 등의 이름을 변형하는 것을 무엇이라 하는가? 
    * 모르겠음. 
    
16. 다음 문장은 main.cpp 파일안의 코드의 일부분. 두 줄의 의미 ? 
    
    ```
       //(1)
    extern void put(char*);
        //(2) 
    extern "C" void print(char*); 
    ``` 
    - (1) put 이란 함수를 프로그램의 모든 파일이 사용할 수 있도록 한다. 함수의 선언부가 알려져 있음. 선언이 있으면 C 컴파일러는 함수의 definition 이 있다는 것을 알아. 
    - (2) `extern "C"` 선언을 통해 C++로 컴파일 할 경우 C언어 구혁임을 명시. 

    * C++은 오버로드 기능 때문에 컴파일시에 함수에 대한 symbol 이름을 조금씩 변경을 함. 
    * C같은 경우 같은 이름의 함수가 존재할 수 없기 때문에 심볼 이름이 동일. 
    * 따라서 함수 하나를 전방 선언하고 사용할 경우 C++ 스타일의 심볼 이름을 찾게 되고, C 함수의 print 심볼 이름과 엇갈리게 되어 링크 오류가 발생
    
17. 같은 이름의 함수를 여러 개 만드는 함수 중복이 불가능한 이유? 
    - [스택 오버플로우 : C에서 오버로딩이 되는가?](https://stackoverflow.com/questions/2351792/does-c-support-overloading)

 

    
